// Code generated by hertz generator.

package main

import (
	"demoProject/dataAccess"
	"fmt"
	"github.com/cloudwego/hertz/pkg/app/server"
	"os"
)

func main() {
	if len(os.Args) < 3 {
		fmt.Println("Need database user and passwd, " +
			"you may be missing parameters or passing too many parameters ")
		return
	}
	dataAccess.USER = os.Args[1]
	dataAccess.PASSWD = os.Args[2]
	//if len(os.Args) < 4 {
	//	fmt.Println("Missing fourth addr parameter")
	//	return
	//}
	//addr := os.Args[3]
	//h := server.Default()
	options := server.WithHostPorts("0.0.0.0:8888")
	h := server.Default(options)
	register(h)
	h.Spin()
}
