// Code generated by hertz generator.

package demoServer

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _examlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _stuinformationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _treestructureMw() []app.HandlerFunc {
	// your code...
	return nil
}

func __llstuinformationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _classknowledgecorrectperMw() []app.HandlerFunc {
	// your code...
	return nil
}
